In [25]:
import pandas as pd

data = {
    "query_name": ["Dog", "Dog", "Dog", "Cat", "Cat", "Cat", "Cat"],
    "result": [
        "Golden retriever",
        "German Shepherd",
        "Mule",
        "Shirazi",
        "Siamese",
        "Sphynx",
        "Sphynx",
    ],
    "position": [1, 2, 200, 5, 3, 7, 7],
    "rating": [5, 5, 1, 2, 3, 4, 4],
}

data = {
    "query_name": ["Dog", "Dog", "Dog", "Cat", "Cat", "Cat", "Cat"],
    "result": [
        "Golden retriever",
        "German Shepherd",
        "Mule",
        "Shirazi",
        "Siamese",
        "Sphynx",
        "Sphynx",
    ],
    "position": [1, 1, 1, 1, 1, 1, 1],
    "rating": [5, 5, 5, 5, 5, 5, 5],
}

data = {
    "query_name": ["Dog", "Dog", "Dog", "Cat", "Cat", "Cat", "Cat", "Monkey"],
    "result": [
        "Golden retriever",
        "German Shepherd",
        "Mule",
        "Shirazi",
        "Siamese",
        "Sphynx",
        "Sphynx",
        "Sphynx",
    ],
    "position": [1, 1, 1, 1, 1, 1, 1, 2],
    "rating": [5, 5, 5, 5, 5, 5, 5, 2],
}

data = {
    "query_name": [
        "pdxafib",
        "mpzkxkzbompbpbavkb",
        "udrcvuaxzjhbnvcyo",
        "xdyoviczumlpchsnsbnwqmljgh",
        "xdyoviczumlpchsnsbnwqmljgh",
        "snhrdtzetlihfenkdjyatadzhskomr",
        "pdxafib",
    ],
    "result": [
        "jwqjgyrnhaptivvnqkj",
        "srlfyprermbgldweweulwdfmbddgarvtdm",
        "hekmecxifwqthvcixhtnxnhjfzwuzbgirrljrdiz",
        "kvrydrjdithfoytworvasqlyjulaolldallexqljk",
        "qkebkugmaikexeuxnaruqrb",
        "ejxukcbau",
        "vcsfpqonshcrzowpcxptnjt",
    ],
    "position": [16, 10, 14, 3, 19, 19, 18],
    "rating": [5, 1, 3, 4, 2, 4, 3],
}

queries = pd.DataFrame(data)

In [26]:
queries["quality"] = queries["rating"] / queries["position"] + 1e-10
queries["poor_quality"] = queries["rating"].apply(lambda x: 1 if x < 3 else 0)
composite_quality = (
    queries.groupby("query_name")
    .agg({"quality": "sum", "poor_quality": "sum"})
    .reset_index()
)
count_num = queries.query_name.value_counts().reset_index()
composite = pd.merge(composite_quality, count_num, on="query_name", how="outer")
composite["poor_query_percentage"] = round(
    (composite["poor_quality"] / composite["count"]) * 100, 2
)
composite["quality"] = round(composite["quality"] / composite["count"], 2)
composite = composite.drop(columns=["poor_quality", "count"])
composite.sort_values(by="query_name", ascending=False)

                       query_name  quality  poor_query_percentage
4      xdyoviczumlpchsnsbnwqmljgh     0.72                   50.0
3               udrcvuaxzjhbnvcyo     0.21                    0.0
2  snhrdtzetlihfenkdjyatadzhskomr     0.21                    0.0
1                         pdxafib     0.24                    0.0
0              mpzkxkzbompbpbavkb     0.10                  100.0

In [27]:
print(queries)
print("\n", composite)

                       query_name                                     result  \
0                         pdxafib                        jwqjgyrnhaptivvnqkj
1              mpzkxkzbompbpbavkb         srlfyprermbgldweweulwdfmbddgarvtdm
2               udrcvuaxzjhbnvcyo   hekmecxifwqthvcixhtnxnhjfzwuzbgirrljrdiz
3      xdyoviczumlpchsnsbnwqmljgh  kvrydrjdithfoytworvasqlyjulaolldallexqljk
4      xdyoviczumlpchsnsbnwqmljgh                    qkebkugmaikexeuxnaruqrb
5  snhrdtzetlihfenkdjyatadzhskomr                                  ejxukcbau
6                         pdxafib                    vcsfpqonshcrzowpcxptnjt

   position  rating   quality  poor_quality
0        16       5  0.312500             0
1        10       1  0.100000             1
2        14       3  0.214286             0
3         3       4  1.333333             0
4        19       2  0.105263             1
5        19       4  0.210526             0
6        18       3  0.166667             0

                        query_name  quality  poor_query_percentage
0              mpzkxkzbompbpbavkb     0.10                  100.0
1                         pdxafib     0.24                    0.0
2  snhrdtzetlihfenkdjyatadzhskomr     0.21                    0.0
3               udrcvuaxzjhbnvcyo     0.21                    0.0
4      xdyoviczumlpchsnsbnwqmljgh     0.72                   50.0